### ISSUE TITLE
assign_view and other operations with view_df: cols argument applied to both df and view_df

### ISSUE THREAD

**Issue by Phlya** [open2c/bioframe#101]
Which annoyingly makes it impossible to assign view to both sides of a bedpe-style DF in two calls with different cols= argument.

Shall we make a second argument? Or only apply it to df and assume standard column names in view_df?

**Comment by gfudenberg** [comment]
Passing cols1 and cols2 arguments to assign_view makes sense to me!

**Comment by Phlya** [comment]
Other ops that use `assign_view` and could benefit from the same fix: `trim`, `complement`, `sort_bedframe`

**Comment by gfudenberg** [comment]
go for it!  Ideally add quick checks for these new args too! 
I'd lean towards cols, cols_view
