### ISSUE TITLE
non-standard column names in checks.is_contained

### ISSUE THREAD

**Issue by Phlya** [open2c/bioframe#126]
Broken at the moment, and also need to add a test for that - probably also for all other checks.

**Comment by gfudenberg** [comment]
I guess "cols_view" should also be passed to is_contained and is_covering ?
https://github.com/open2c/bioframe/blob/ebefad643023695223105ad799a6165c97b0d4e4/bioframe/core/checks.py#L358

`complement` does accept "cols_view": https://bioframe.readthedocs.io/en/latest/api-intervalops.html#bioframe.ops.complement


and for the test(s), I guess we would then need one that passes is_contained with non-standard column names (e.g. chrom1, start1, end1), as well as passes is_covering with non-standard view_names (e.g. CHR, START, END)
