### ISSUE TITLE
Change in goldenpath URL

### ISSUE THREAD

**Issue by nvictus** [open2c/bioframe#186]
UCSC seems to have migrated goldenpath from: 

https://hgdownload.cse.ucsc.edu/goldenPath/
to
https://hgdownload.soe.ucsc.edu/goldenPath/

If this is correct, we'll have to change all URLs used in fetchers and in the docs.

**Comment by golobor** [comment]
the new URL seems to work. I took the liberty of commiting the fix straight into main. Please, let me know if it still does not work!
