### ISSUE TITLE
Add a function to make a binned table with gene density

### ISSUE THREAD

**Issue by golobor** [open2c/bioframe#4]

**Comment by sergpolly** [comment]
is it the function ? `gene_coverage` is the same as `gene_density` or not ?

https://github.com/mirnylab/bioframe/blob/c1e3867116a4bb1448e287b3a4f0be8273d771b7/bioframe/tools.py#L166

as mentioned https://github.com/mirnylab/cooltools/pull/22 there are issues, but overall it's working.
I made it to work by manually defining `bedtools` wrapper: https://github.com/mirnylab/bioframe/blob/c1e3867116a4bb1448e287b3a4f0be8273d771b7/bioframe/tools.py#L329

**Comment by golobor** [comment]
yup, this function reports the fraction of each bin covered by at least one gene and the number of genes overlapping a bin. Empirically, the latter gives the most reliable phasing, all other measures failed for me at least once on some dataset. Also, the advantage over "gc" is that it's much easier to generate.
Btw, did you commit the fix? I don't have the same issue, so i'm not sure where it could come from!

**Comment by gfudenberg** [comment]
it seems this issue should be closed? cc @golobor

**Comment by gfudenberg** [comment]
re-open if you need!
