### ISSUE TITLE
bioframe.closest drops values if chromosome is missing in other

### ISSUE THREAD

**Issue by mimakaev** [open2c/bioframe#45]
in `bioframe.closest(a,b)`   the result is usually the same length than a. However, if some chromosome is missing in b but is in a, the result is smaller. This is dangerous! 

![image](https://user-images.githubusercontent.com/9454715/86478282-689dda00-bd20-11ea-92a4-7ac73b6f846b.png)

Related but different issue: why don't we index the result by default with the index of a? This will prevent so so so many bugs! (I just had two in a row!)

Correct me if I'm wrong, but (one of) the most likely use case of closest would proceed as follows: 

```
result = bioframe.closest(mydf, other_df)
do-something-to-result 
mydf["new_column"] = result["some_column"]  # option 1 or ... 
mydf["new_column"] = result["some_column"].values  # option 2 

```

Right now both options 1 and 2 would usually work, but sometimes silently fail for two reasons. One is missing chromosome (both fail). Second is if the result is indexed differently than mydf! (if mydf is a slice and is indexed with [1,2,4,6,9,14,15]). First will fail silently, but second will work unless there are missing chromosomes. And if it is a mostly-complete slice, when you display the .head(), you won't even notice the bug. I just experienced both versions... 

In my experience, pandas preserves the original index and length with .join(), but not with .merge(). So .join-like operations should comply with .join: same length and original index, while .merge()-like operations should allow for different length and no original index.

**Comment by golobor** [comment]
(a) should we return NA when the entire - chromosome is missing from b? I would vote for it.

(b) as much as I understand, preserving indexing would be impossible for k>1? We could preserve indexes for k=1. But, I would be concerned that this would make the function less predictable. What do others think?

**Comment by gfudenberg** [comment]
I agree with (a), & just implemented it.

as for (b), we have a `keep_order=False` default for `overlap()`. 

I don't have a strong feeling about this, but they probably should be congruent.  
- should we add this option to closest(), set it false, and require k=1 to use it? or let the user return_index and then sort?
- relatedly, should overlap throw an error if `keep_order=True `and how is not 'left'?

**Comment by gfudenberg** [comment]
closing this, since (a) was addressed and my question about `overlap` was addressed (the default behavior of overlap was changed as well). Feel free to re-open, though!
