### ISSUE TITLE
value types casting issues, pd.NA and pd.Categorical ....

### ISSUE THREAD

**Issue by sergpolly** [open2c/bioframe#46]
a little snippet below is an example of my issues with `bioframe.ops.overlap` :
1. couldn't cast `pd.NA` to `float`
2. `chrom,start,end` became `object` and `pd.Categorical` somehow - which made `groupby` without `observed=True` impossible

I'm not sure what of that is expected behavior and what isn't ...
I'll fill in this example with actual data later

```python
from bioframe import io
timfname = "filename"
bins = clr.bins().fetch(chrom).copy()
val_rt = io.read_table(timfname, schema=bioframe.schemas.BEDGRAPH_FIELDS, skiprows=1)
val_rt = val_rt.rename({0:"chrom",1:"start",2:"end",3:"rt"}, axis=1)

# overlap RT signal with our bins ...
binned_rt = bioframe.ops.overlap(bins, val_rt, suffixes=['', '_rt'])
# freaking pd.NA !? can't cast them to float ... why ? why are they there in the first place ?!
binned_rt["value_rt"] = binned_rt["value_rt"].apply(lambda x: np.nan if x is pd.NA else x)

binned_rt = binned_rt \
                .drop(labels=["chrom_rt","start_rt","end_rt"],axis=1) \
                .astype({"start":int,"end":int,"weight":float})
# finally :
binned_rt = binned_rt.groupby(["chrom","start","end"],observed=True,sort=False).mean()
```

**Comment by sergpolly** [comment]
this boils down to 2 things:
1.  `cooler.bins()[:]`  stores `chrom` as `Categorical` and it creates "problems" when `groupby` - can be solved by doing `groupby(...observed=True)`, requires user to be aware - so not a problem after all - related to #47 
2. second is the novelty and lack of understanding regarding `pd.NA` - boils down to `np.float(pd.NA)` - raising an error ...

more examples regarding the 2:
 - `pd.Series([.0,pd.NA, np.nan])` would have `dtype=object` and is impossible to case to `float`
 - `pd.Series([.0,pd.NA, np.nan],dtype='float)` raises an error
 - `pd.Series([0,pd.NA, np.nan]).to_numpy(na_value=np.nan).astype(float)` - this works ...

**Comment by sergpolly** [comment]
seems relevant https://github.com/pandas-dev/pandas/issues/32265

turns out `pd.NA` - can be easily cast to special pandas int - `Int64`, but not to `float`- there is no special pandas-float type - and the whole thing is being discussed now on pandas side

**Comment by sergpolly** [comment]
here is more conext , example of where `pd.NA` appears:
![Screenshot from 2020-07-17 13-09-10](https://user-images.githubusercontent.com/6790270/87812908-f1436c80-c82e-11ea-83d5-0806585ef25e.png)

once, I have `pd.NA` in my `value_rt` - it turns into `dtype=object`, and I cannot cast it back to `float` (easily),  and cannot do "math" with it

**Comment by golobor** [comment]
a possible solution: add a flag fill_na=False. If True, fill NAs with corresponding NaN-like values for each type.

**Comment by gfudenberg** [comment]
ops.overlap now by default casts start2 & end2 as `pd.Int64Dtype()` when [how != inner](https://github.com/open2c/bioframe/blob/eeda0dc94ce4658f933e86cc7c881f5d65ea41dc/bioframe/ops.py#L389), and a float values column stays as a float :

```python 

df1 = pd.DataFrame(
    [
        ["chr1", 8, 12, "+",],
        ["chr1", 8, 12, "-"],
        ["chrX", 1, 8, "+"],
    ],
    columns=["chrom", "start", "end", "strand"],)

df2 = pd.DataFrame(
    [["chr1", 6, 10, "+", 1.5], 
     ["chrX", 7, 10, "-", 2.2]],
    columns=["chrom", "start", "end", "strand","value"],)

b = bioframe.overlap(
    df1,
    df2, how='left', on=['strand'])

b.dtypes
```

> chrom_1      object
start_1       Int64
end_1         Int64
strand_1     object
chrom_2      object
start_2       Int64
end_2         Int64
strand_2     object
value_2     float64

So I think this is resolved, but please re-open if not!
