### ISSUE TITLE
bioframe.closest (and perhaps other functions) break when working with categorical chromosomes

### ISSUE THREAD

**Issue by mimakaev** [open2c/bioframe#47]
cooler.bins() returns chrom column as categorical. 

If one is then to filter chroms (e.g. bins = bins[bins["chrom"] != "chrM")  then "chrM" actually is left in the categorical variable, and would be a part of the .groupby(), even though the corresponding group is length 0. 

Maybe this https://github.com/mirnylab/bioframe/blob/develop/bioframe/ops.py#L833  and similar places need a check for whether the group is empty?

**Comment by sergpolly** [comment]
@mimakaev this is what I observed as well - #46 - you can use `observed=True` to avoid grouping by non-existent categories

**Comment by sergpolly** [comment]
ok, #46 is unrelated, but `groupby(...observed=True)` approach for grouping categoricals could be an alternative

**Comment by gfudenberg** [comment]
groupby(... observed=True) has now been implemented!

tests added for subtract and closest
