### ISSUE TITLE
can we have to_ucsc of some sort somewhere ?

### ISSUE THREAD

**Issue by sergpolly** [open2c/bioframe#50]
in an effort to unify handling of regions throughout cooltools/bioframe we should have something like `to_ucsc` formatter somewhere , shoudn't we ?

e.g. to avoid code like that: `regions.apply(lambda x: "{}:{}-{}".format(*x), axis=1)` ...

There is something in cooler i believe but should it be in bioframe instead ?

**Comment by gfudenberg** [comment]
this should now be in bioframe.core.stringops
