### ISSUE TITLE
split drops intervals that do not contain a splitting point

### ISSUE THREAD

**Issue by golobor** [open2c/bioframe#54]
https://github.com/open2c/bioframe/blob/22675199efd1ee80304ed31a108505d84341d5ab/bioframe/ops.py#L1193

@gfudenberg  , I forgot if we discussed it, but is that really the desired behaviour? In the standard application, splitting of chromosomes into arms, this setting leads to an omission of chromosomes for which centromeres are not specified. 
Overall, this seems counter-intuitive to me... I would suggest  (a) adding an argument to retain non-split intervals and (b) setting it to True by default. What do you and others think?

**Comment by gfudenberg** [comment]
I don't think we discussed this aspect of split(). It looks like there is an item in the roadmap todo that involved circling back to split after finalizing subtract. I remember we had some discussion for complement about default behavior if chromsizes were not provided. Can't recall if we resolved that 100%. 

All that said-- the default behavior you propose makes sense to me!

**Comment by golobor** [comment]
fixed in https://github.com/open2c/bioframe/commit/43d3d6d8491e289beee62039ee6b0f1d01f09feb

**Comment by golobor** [comment]
I didn't add an option to drop non-split intervals, b/c it's currently hard to tell if an interval became split or not

**Comment by golobor** [comment]
closing for now, @gfudenberg feel free to reopen if needed
