### ISSUE TITLE
add make_pairs() function

### ISSUE THREAD

**Issue by golobor** [open2c/bioframe#55]
https://github.com/open2c/cooltools/blob/19bf4c169826e4bf1336229c71cfb8a0947c924e/cooltools/snipping.py#L206

**Comment by golobor** [comment]
(a) allow users to specify distance in sites, not bp
(b) add flexible suffixes

**Comment by gfudenberg** [comment]
I believe the recent PR closes this:
https://github.com/open2c/bioframe/commit/94a9fcd42fe668f72faecd68a2f0b3c3603a1e91
(now called pair_by_distance)
https://github.com/open2c/bioframe/blob/94a9fcd42fe668f72faecd68a2f0b3c3603a1e91/bioframe/ops.py#L1331z
