### ISSUE TITLE
in slice_bedframe and everywhere else, allow providing an unparsed region

### ISSUE THREAD

**Issue by golobor** [open2c/bioframe#6]
https://github.com/mirnylab/bioframe/blob/bbfbd18de489cf06c6b735845acd40be794d57bc/bioframe/core.py#L191

**Comment by gfudenberg** [comment]
seems like this should now be supported in bioframe.select
https://github.com/open2c/bioframe/blob/94a9fcd42fe668f72faecd68a2f0b3c3603a1e91/bioframe/ops.py#L60
