### ISSUE TITLE
should frac_gene be rename frac_RNA?

### ISSUE THREAD

**Issue by gspracklin** [open2c/bioframe#64]
https://github.com/open2c/bioframe/blob/94a9fcd42fe668f72faecd68a2f0b3c3603a1e91/bioframe/genomeops.py#L283

I naively assumed that frac_gene was using unique genes, not all predicted and verified RNA isoforms.

**Comment by gfudenberg** [comment]
I wonder if this function should just be deprecated. With more & more transcripts, the current implementation gets less & less useful-- e.g. I typically add some filter on expression level within a matched tissue.

**Comment by golobor** [comment]
@gfudenberg ,  this function was written to provide an alternative way to phase and sort eigenvectors, for organisms where the GC is not well correlated with activity. It worked well for me in flies! Of course, one can be more precise if one has RNA-seq, but (a) such datasets are not always available and (b) I'm not sure if it'd bring major improvements (that would require testing). But I may be missing something important here!

**Comment by gfudenberg** [comment]
fair point that this can be more useful for other organisms. 

how about a more informative title than just frac_RNA, e.g. `frac_all_mrna_UCSC()` or `frac_UCSC_all_mrna()`  ? cc @gspracklin

**Comment by gfudenberg** [comment]
docstring updated in #106, closing for now.
