### ISSUE TITLE
fetch_chromsizes(as_bed=True) doesn't reset index of returned DataFrame - should it?

### ISSUE THREAD

**Issue by sergpolly** [open2c/bioframe#68]
`bioframe.fetch_chromsizes` pulls a filtered subset of chromosomes (ignoring contigs and such) in a "natural" order - but it does not reset a DataFrame index - so it is out of order and non-contiguous e.g. chrM is ~249 for hg19 - should we reset index before returning a dataframe ?

!!! true - only when using `as_bed=True` !!! - `as_bed = False` yields a `chrom` indexed DataFrame

would be as simple as adding `.reset_index(drop=True)` at the end of this line:
https://github.com/open2c/bioframe/blob/94a9fcd42fe668f72faecd68a2f0b3c3603a1e91/bioframe/io/formats.py#L138

**Comment by golobor** [comment]
Oh!! Please, feel free to commit!
