### ISSUE TITLE
io.to_bed()

### ISSUE THREAD

**Issue by golobor** [open2c/bioframe#72]
it'd be super nice to have a function that saves a bedframe into a bed file and resorts columns, potentially drops those not compatible with the bed format and formats the comment line.

**Comment by nvictus** [comment]
Just leaving a useful recipe for assigning to the `itemRgb` column:

```python
from matplotlib.colors import to_rgb

def to_ucsc_colorstring(color):
    return ','.join(str(int(x*255)) for x in to_rgb(color))
```

**Comment by nvictus** [comment]
Here's a prototype: https://gist.github.com/nvictus/1871b9672878b3115dc7e903eb027c93
