### ISSUE TITLE
standardize functions to read various "bioframes" from file

### ISSUE THREAD

**Issue by sergpolly** [open2c/bioframe#73]
related to "define bioframe standards" item of the current roadmap: https://github.com/open2c/bioframe/issues/48

in cooltools CLI (and when working with real data in a notebook) we have some reoccurring "read-from-file" patterns:
 - read "regions"  dataframe (in a cooler-compatible fashion) - e.g.  in [compute-expected](https://github.com/open2c/cooltools/blob/68090d6e650b069d2439bbceced467b4ae6b920b/cooltools/cli/compute_expected.py#L125) , [soon](https://github.com/open2c/cooltools/pull/245) in call-compartments, in [compute-saddles](https://github.com/open2c/cooltools/blob/68090d6e650b069d2439bbceced467b4ae6b920b/cooltools/cli/compute_saddle.py#L224), in [call-dots](https://github.com/open2c/cooltools/blob/68090d6e650b069d2439bbceced467b4ae6b920b/cooltools/cli/call_dots.py#L208) ... also in [dump-cworld](https://github.com/open2c/cooltools/blob/master/cooltools/cli/dump_cworld.py) apparently ... and of course - pile-ups ! maybe coolpuppy ?
 - read "reference-track" (bedGraph) in a cooler-compatible fashion for [compartment flipping/sorting](https://github.com/open2c/cooltools/blob/68090d6e650b069d2439bbceced467b4ae6b920b/cooltools/cli/call_compartments.py#L75) and for [saddle calculation](https://github.com/open2c/cooltools/blob/68090d6e650b069d2439bbceced467b4ae6b920b/cooltools/cli/compute_saddle.py#L327),
 - maybe reading some plain BED/BEDPE files e.g. for pile-ups ?!
 - reading "expected" in a cooler and regions-compatible fashion (does "expected" belong to "bioframe" standards ? - distance summary for _cis_, or BEDPE-like summary for _trans_ ) in call-dots, in compute-saddles - something else (?)

We clearly need those functions in cooltools, but the question is if they need to be defined in `bioframe` ?
 ... Probably not, as making "read-from-file" functions that check for compatibility with cooler should be outside the scope of "bioframe" ...
However,  implementing functions like that would require "bioframe" defined standards and checks for sure, like:
 - is reference-track "tiling" and "sorted" ?
 - are "regions" non-overlapping ? named or require naming ?
 - what else ?

Last point - "read-from-file" functions like these can maybe reside in `bioframe` only if they check for cooler-compatibility indirectly - e.g. via "chrom-sizes" and/or "binsize" in case we want or check alignment to bins

**Comment by gfudenberg** [comment]
I'm not 100% sure what you mean in the first 3 bullets-- these can be read in w/ bioframe.read_table(file, schema=file_format)
see this ipynb for an example: https://github.com/open2c/bioframe/blob/master/docs/notebooks/tutorial_assign_motifs_to_peaks.ipynb
https://github.com/open2c/bioframe/blob/master/bioframe/io/schemas.py
https://github.com/open2c/bioframe/blob/master/bioframe/io/formats.py

If you have suggestions for better documenting this functionality, that would be great!

For the fourth bullet point, my suggestion would be that expected from cooler/cooltools would be a format for those libraries, not for bioframe.

For last 3 points, check out my PR-- any suggestions would be helpful, from docstrings on up!
https://github.com/open2c/bioframe/pull/71

(I still need to add sorting before I bug @golobor about merging, planning to do that today)

**Comment by sergpolly** [comment]
Ok, here is what I meant in the 1 bullet, regarding `regions` :
here is an operation that we do in several cooltools CLI, which would be nice to wrap into io-API that does the following:
```python
read_regions(
    "name.bed", # 3-4 column BED file, w/o header - handle all cases automatically
    cool_compatibility_check = None, # check compatibility with cooler - same chroms, sizes are legit
    chromsizes_compatibility_check = None, # check compat with a DF of chromsizes as alternative to cool
    allow_overlapping = False, # most of the time cooltools would require non-overlapping regions
    more_checks =? ...
)
```
so far we've been doing it like this in several cooltools CLI:
```python
        regions_buf, names = util.sniff_for_header(regions)
        regions_table = pd.read_csv(regions_buf, sep="\t", header=None)
        if regions_table.shape[1] not in (3, 4):
            raise ValueError(
                "The region file does not have three or four tab-delimited columns."
                "We expect a bed file with columns chrom, start, end, and optional name"
            )
        if regions_table.shape[1] == 4:
            regions_table = regions_table.rename(
                columns={0: "chrom", 1: "start", 2: "end", 3: "name"}
            )
            regions_table = bioframe.parse_regions(regions_table)
        else:
            regions_table = regions_table.rename(
                columns={0: "chrom", 1: "start", 2: "end"}
            )
            regions_table = bioframe.parse_regions(regions_table)
```
that is not ideal, imho - we copy/paste that around changing it every so slightly and it would be better to have it "standardized" - perhaps in the context of cooltools, not in bioframe ...

I see about the `bioframe.read_table` ! I think we could leverage that more in cooltools ...
maybe like that:
```python
try:
    regions = bioframe.read_table(regions, schema="bed4")
except ParserError:
    regions = bioframe.read_table(regions, schema="bed3")
...
```
So I guess this was more of a cooltools question/discussion to begin with - we need to implement those repeating read from file patterns in cooltools using functionalty and formats provided by bioframe ...
Sorry for polluting the "issues" of bioframe with this !

**Comment by gfudenberg** [comment]
the version with `bioframe.read_table` looks nice! 
also, check out [`bioframe.core.construction.from_any()`](https://github.com/open2c/bioframe/blob/a4758de8d6cd74af60a50022604be3a77d119c27/bioframe/core/construction.py#L63) for interconverting between dicts etc. (it is a refactored version of `parse_regions`) 

closing this issue for now
