### ISSUE TITLE
provide a unified method to fetch centromeres

### ISSUE THREAD

**Issue by golobor** [open2c/bioframe#8]
Several cooltools need to know the locations of centromeres. Thus, we need a function that would automatically fetch them and bioframe seems like the best library for it.

The biggest obstacle is that there is no standard file in goldenPath whose purpose would be to store centromeres. Several files may or may have centromeres (cytoband, gap, agp), but there is never a dedicated file that would work for all assemblies. Moreover, for some assemblies, like sacCer3, we'd need to use other resources besides UCSC.

So, the solution that I propose is to query centromeres in three steps:
(1) include centromeres for the model organisms (humans, mice (acro), zebrafish, drosophila (none), c.elegance, baker's and fission yeast, arabidopsis) into bioframe itself.
(2) if (1) fails, fetch and parse cytoband file from UCSC
(3) if (2) fails, fetch and parse gap

Also, since centromeres are extended regions, store them as (chrom, start, end, mid).
ping @nvictus

**Comment by golobor** [comment]
the proposed solution can be found at https://gist.github.com/golobor/2d0dbeb331899aa1bb68912c751f2f4f
(continuously updated)

**Comment by nvictus** [comment]
Looks good. I would propose that the implementations of (2) and (3) do not "fetching", since obtaining those inputs can be done separately.
i.e. `centromeres_from_cytoband()` and `centromeres_from_gapfile()`.

**Comment by golobor** [comment]
sounds right! Thanks, will do!

**Comment by gfudenberg** [comment]
what's the desired behavior for:
- mouse centromere fetching? raise ValueError("mouse chromosomes are acrocentric") ?
- drosophila chromosomes? (currently returns nothing since e.g. 2L and 2R are split in the table
- organisms where it silently fails (currently, panTro6, sacCer3)? add a check that len(df_centromeres) >= (len(df_chromsizes)-2) (for Y & mitochrondria?)

**Comment by gfudenberg** [comment]
updated docstring for fetch_centromeres to note that it     currently only works for human assemblies.
