### ISSUE TITLE
from_* constructors behavior is inconsistent with the type of input - should not generate name-column by default

### ISSUE THREAD

**Issue by golobor** [open2c/bioframe#80]
https://github.com/open2c/bioframe/blob/1e1cd8df34b2e31d90e1294086594a4ff99065e5/bioframe/core/construction.py#L63

**Comment by gfudenberg** [comment]
would you suggest implementing as ``name_col=None``?

**Comment by sergpolly** [comment]
if you pass a DataFrame with `chrom, start, end` without the any `name` then `from_any` does not enforce any `name`

**Comment by sergpolly** [comment]
Actually, it is more nuanced - here is an inconsistency - e.g. if you pass a list of UCSC formatted regions - then `from_any` generates correct DataFrame AND forces `names` (regardless of the `name_as_ucsc` flag):
```python
xxx = list(bioframe.from_any(hg19_chromsizes,names_as_ucsc=True)["name"].values)
bioframe.from_any(xxx) # -> 4-column DataFrame ... 
```

applies to other input types as well, except from DataFrame 3-col input

**Comment by gfudenberg** [comment]
`from_any` no longer forces names in 0.3.0-- only `make_viewframe` does
![image](https://user-images.githubusercontent.com/19657573/129397929-6d366ad4-b790-4abc-859d-c27fff551a87.png)
