### ISSUE TITLE
fetch_centromeres error

### ISSUE THREAD

**Issue by skytguuu** [open2c/bioframe#84]
Hi,

Thanks for your developed tool. Recently, I met a problem about the fetch_centromeres. When I tried the command 'bioframe.fetch_centromeres('mm9')', it reported an error :
##########
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dell/softwares/anaconda2/envs/py36/lib/python3.6/site-packages/bioframe/io/resources.py", line 122, in fetch_centromeres
    raise ConnectionError("No internet connection!")
ConnectionError: No internet connection!
##########
Could you give me a hand?
Thanks

**Comment by Phlya** [comment]
Did you have internet connection?..

**Comment by skytguuu** [comment]
Thanks for your prompt reply. I have checked my internet, it works. However, the google was block on my network, while other websites: ucsc genome browser can be connected. When i tried the vpn to use the google, it is still reported the same error.
Any idea?

**Comment by nvictus** [comment]
That's because it pings Google to verify connectivity, which was a poor assumption, given circumstances like yours. It will be removed in the next release. In the meantime you could try monkey patching:

```python
import bioframe
bioframe.io.resources._check_connectivity = lambda *a, **kw: True
...
```

**Comment by xiasijian** [comment]
Thanks
