### ISSUE TITLE
is_contained limitations: cannot check if arms/regions are contained in the chromosomes

### ISSUE THREAD

**Issue by sergpolly** [open2c/bioframe#85]
Currently `is_contained` allows for "containment" checking only between 2 dataframes (viewframes?) that both have "name"-column (or similar) and such "names" of the `df` are cataloged in `view_df` .

This might be limiting, as for example it prevents us from checking if a set of regions (e.g arms) is contained within chromosomes:
```python
make_viewframe(arms_df, check_bounds=chromsizes_df)
```
fails with the "not cataloged" error

**Comment by sergpolly** [comment]
thinking about it - adding a bit more functionality to `is_contained` would be easiest ...

something like `is_contained(...,view_df, chromsizes=None...)` , where `view_df` doesn't have to be provided or is incompatible with `chromsizes`

**Comment by sergpolly** [comment]
suggestion:

if `df_view_col` is not provided (switch default to `None`) then allow `is_contained` to compare intervals using overlap like so:
```python
df_view_assigned = bioframe.overlap(hg19_arms, hg19_chromsizes)
assert (df_view_assigned["end"]<=df_view_assigned["end_"]).all()
assert (df_view_assigned["start"]>=df_view_assigned["start_"]).all()
```

```python
bioframe.is_contained(
    df,
    view_df,
    raise_errors=False,
    df_view_col='view_region',
    view_name_col='name',
    cols=None,
)
```

**Comment by gfudenberg** [comment]
thanks for the suggestion! updated in 0.3.0
https://github.com/gfudenberg/bioframe/blob/129b5f60407fe68b228156759f5ab6e393ada9cd/bioframe/core/checks.py#L286
