### ISSUE TITLE
make_viewframe has to fill names column by default by comply with viewframe definition

### ISSUE THREAD

**Issue by sergpolly** [open2c/bioframe#87]
Right now `make_viewframe` does not auto-generate `name` column , unless specifically asked to  (at least when input is a 3-column DataFrame) ...

It  should, though, because `viewframe` is defined as a 4-column "table"

**Comment by gfudenberg** [comment]
updated in 0.3.0!
![image](https://user-images.githubusercontent.com/19657573/129397780-eecb27be-8b62-4f98-af04-51f22d7013c5.png)
