### ISSUE TITLE
is_sorted(df, clr.chromsizes) returns False because of extra column and dtypes change

### ISSUE THREAD

**Issue by sergpolly** [open2c/bioframe#94]
following our discussion on 9/15/21:
`is_sorted(sorted_hg19_arms, clr.chromsizes, df_view_col=None,)` returns `False`, instead of `True` - because inside `is_sorted` - sorting of `sorted_hg19_arms` is attempted, and 1 extra column `view_region` is added to the result - in the end `df.equals(sorted_df)` is `False` only because of that additional column ...

Should it be something like:
```python
cols = ("chrom","start","end")
df[cols].equals(sorted_df[cols])
```
inside of `is_sorted` instead?

**Comment by sergpolly** [comment]
@gfudenberg stupid me - i'm so sorry - I didn't even check if #95 was enough to make it work ...
turns out `df_view_col=None` triggers more changes - `assign_view` , which internally triggers `overlap` - which in turn changes `dtypes` of `start,end` from whatever `int64/32` they are to `pd.Int64Dtype` !!!
which in turn makes `df.equals(sorted_df[df.columns])` return `False`  only because of the type differences

`pandas.DataFrame.equals` seems very strict , but if we're sticking with it - do you think something like:
```python
df.equals(sorted_df[df.columns].astype(df.dtypes))
```
would be ok ? that definitely works, checked!

PS
I saw bioframe tests are also full of these `pd.Int64Dtype` conversions, so I guess you've dealt with this issue quite a bit before))

**Comment by Phlya** [comment]
https://stackoverflow.com/a/65327466/1304161 another possibility

**Comment by sergpolly** [comment]
i wish they had this `check_dtypes` flag in the `pd.DataFrame.equals` method itself ...
it's just that inserting from `pandas.testing` module and then trying to catch `AssertionException` looks  a bit too much, no ?

There is also an element-wise comparison method `pd.DataFrame.eq`, but this would require `.all().all()` at the end ...

here is the contest:

```python
#1 
df.equals(df_sorted[df.columns].astype(df.dtypes))

#2
df.eq(df_sorted[df.columns]).all().all()

#3 
from pandas.util.testing import assert_frame_equal
_is_sorted = True
try:
    assert_frame_equal(df, df_sorted, check_dtype=False)
except AssertionError:
    _is_sorted = False

```
so 1, 2 or 3 ?

**Comment by Phlya** [comment]
Perhaps whatever we decide on, we could wrap in a bioframe function to reuse everywhere?

**Comment by gfudenberg** [comment]
#1 seems to be nicely readable to me!

**Comment by sergpolly** [comment]
sounds good ! Yeah I guess we can wrap some of that into tiny
```python
bioframe.is_equal_OR_equal_intervals_OR_something_like_that(
    df1,
    df2,
    check_dtypes=False, 
    compare_coordinates_only=True, # compare chrom,start,end and ignore other columns ...
    cols1=None,
    cols2=None
)
```
something like that ?
for now, I guess i'll just commit a quick fix to `main` branch if that's ok
