### ISSUE TITLE
right now pysam dependency is failing with Python=3.9

### ISSUE THREAD

**Issue by sergpolly** [open2c/bioframe#96]
Python=3.9 causes pysam installation to crash for whatever reason

currently `pysam` is required for a number of very specific `io` operations - reading pairix, tabix, bam etc

should this be supported or should bioframe get leaner ? contrib-approach ?

**Comment by nvictus** [comment]
Actually, it's already not a hard dependency, only a development dependency for testing (see `requirements.txt` vs `requirements-dev.txt`).

**Comment by nvictus** [comment]
It's failing in the py39 environment during compilation. I bet there are pre-compiled wheels for earlier pythons and that's why the other envs don't fail. So we could just wait it out...

**Comment by sergpolly** [comment]
but tests use `-dev` one

**Comment by gfudenberg** [comment]
looks like waiting it out worked (tests are passing)-- feel free to reopen though!

**Comment by nataquinones** [comment]
The conda installation for python 3.10 is still failing due to pysam.

```
Looking for: ['bioframe=0.4']

bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
pkgs/main/linux-64                                            No change
pkgs/main/noarch                                              No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change

Pinned packages:
  - python 3.10.*


Could not solve for environment specs
Encountered problems while solving:
  - package bioframe-0.4.0-pyhdfd78af_0 requires pysam, but none of the providers can be installed

The environment can't be solved, aborting the operation
```
