### ISSUE TITLE
Link In Tutorial Not Updating 

### ISSUE THREAD

**Issue by vbchavali** [open2c/bioframe#98]
While running tutorial_assign_motifs_to_peaks.ipynb
I'm getting an error: In[22]

HTTPError: HTTP Error 404: Not Found
The current URL is: 
jaspar_url = 'http://expdata.cmmt.ubc.ca/JASPAR/downloads/UCSC_tracks/2018/hg38/tsv/'
jaspar_motif_file = 'MA0139.1.tsv.gz'

Has the Jaspar url been updated?

**Comment by gfudenberg** [comment]
closed with #99
